# Generated by Django 4.2 on 2026-04-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0003_program_delete_promgram'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Program.program')),
            ],
            options={
                'unique_together': {('program', 'date')},
            },
        ),
    ]
