# Generated by Django 4.2.16 on 2026-04-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Program', '0004_workoutdaylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prgram_data', to='Program.program')),
            ],
        ),
    ]
