# Generated by Django 4.2.16 on 2026-04-07 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Program', '0005_programdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
