# Generated by Django 6.0.3 on 2026-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], default='man', max_length=30)),
                ('progam_goal', models.CharField(choices=[('lossfat', 'lossfat'), ('bulk', 'bulk'), ('cut', 'cut')], default='lossfat', max_length=30)),
                ('durations', models.CharField(choices=[('1 Month', '1 Month'), ('2 Month', '2 Month'), ('3 Month', '3 Month'), ('4 Month', '4 Month'), ('5 Month', '5 Month')], default='2 Month', max_length=30)),
                ('training', models.CharField(choices=[('1 day', '1 day'), ('2 day', '2 day'), ('3 day', '3 day'), ('4 day', '4 day'), ('5 day', '5 day')], default='3 day', max_length=25)),
                ('height', models.CharField(max_length=3)),
            ],
        ),
    ]
