# Generated by Django 6.0.3 on 2026-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promgram',
            name='weight',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
